// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHgSR1v13Yz21Pe7_efX2AjttBxcLROYM',
    appId: '1:407447437020:web:c7af5a41a622f663783e19',
    messagingSenderId: '407447437020',
    projectId: 'schoolease-ac2db',
    authDomain: 'schoolease-ac2db.firebaseapp.com',
    storageBucket: 'schoolease-ac2db.appspot.com',
    measurementId: 'G-KK63X54RG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoo0BQR4O3YNuD5eQ6lQhJwMGGnTqsLAs',
    appId: '1:407447437020:android:9eaeabe968c630d3783e19',
    messagingSenderId: '407447437020',
    projectId: 'schoolease-ac2db',
    storageBucket: 'schoolease-ac2db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC2gPRv4JrIJpKXk95CNSGQrfWWwBPVoU',
    appId: '1:407447437020:ios:e5e4cac4f3813e28783e19',
    messagingSenderId: '407447437020',
    projectId: 'schoolease-ac2db',
    storageBucket: 'schoolease-ac2db.appspot.com',
    iosClientId: '407447437020-li4sqvdb238tjt0j2mivtr01eh3np5ve.apps.googleusercontent.com',
    iosBundleId: 'com.example.se2',
  );
}
